version: '3'

services:
  djangoapp:
    env_file:
      - .env
    build: .
    command: ./start.sh
    volumes:
      - .:/home/itechart_project
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:11.3
