version: '3'

services:
  djangoapp:
    env_file:
      - .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project/src/itechart_project
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
