version: '3'

services:
  djangoapp:
    image:
      itechart_project_djangoapp:latest
    env_file:
      - .env
    build: .
    volumes:
      - .:/home/itechart_project
      - /staticfiles:/staticfiles
    command: ./start.sh
    depends_on:
      - db
      - celery
    networks:
      - nginx_network
      - db_network
      - redis_network

  nginx:
    image: nginx:1.17
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - /staticfiles:/staticfiles
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  db:
    image: postgres:11.3
    networks:
      - db_network

  celery:
    image: itechart_project_djangoapp:latest
    command: celery -A itechart_project worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - .:/home/itechart_project
    networks:
      - db_network
      - redis_network

  celery-beat:
    env_file:
      - .env
    image: itechart_project_djangoapp:latest
    command: celery -A itechart_project beat -l info
    depends_on:
      - redis
      - db
    volumes:
      - .:/home/itechart_project
    networks:
      - db_network
      - redis_network

  redis:
    image: redis:5.0
    networks:
      - redis_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
  redis_network:
    driver: bridge
